services:
    db:
        build:
            context: .
            dockerfile: dockerfile-sql
        ports: 
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PWD}
            MYSQL_DATABASE: ${DB_NAME}
    
    app:
        depends_on:
            - "db"
        build:
            context: .
            dockerfile: dockerfile-app
        ports: 
            - "8080:8080"
        environment:
            DB_HOST: "db:3306"
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PWD: ${DB_PWD}
            SESSION_KEY: ${SESSION_KEY}

volumes:
    db_data: